//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string Description { get; set; }
        public double Price { get; set; }
        public int QntyOnHand { get; set; }
        public double SelfCost { get; set; }
        public double TotalValue { get; set; }
        public int ID { get; set; }
        public int ItemN { get; set; }
    }
}
